apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  hackers-api:
    if: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-api']['cloudbeesdemo/harckers-organized-appro-api'].deploy }}
    uses: cb-golden-demo-org/harckers-organized-appro-api/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-api']['cloudbeesdemo/harckers-organized-appro-api'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-api']['cloudbeesdemo/harckers-organized-appro-api'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
  hackers-auth:
    if: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-auth']['cloudbeesdemo/harckers-organized-appro-auth'].deploy }}
    uses: cb-golden-demo-org/harckers-organized-appro-auth/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-auth']['cloudbeesdemo/harckers-organized-appro-auth'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-auth']['cloudbeesdemo/harckers-organized-appro-auth'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
  hackers-web:
    if: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-web']['cloudbeesdemo/harckers-organized-appro-web'].deploy }}
    uses: cb-golden-demo-org/harckers-organized-appro-web/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-web']['cloudbeesdemo/harckers-organized-appro-web'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['harckers-organized-appro-web']['cloudbeesdemo/harckers-organized-appro-web'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
